highlighter: rouge
kramdown:
  syntax_highlighter: rouge
collections_dir: collections

collections:
  resources:
    output: true
    permalink: /:collection/:name
  music:
    output: true
    permalink: /:collection/:name

sass:
  sass_dir: _sass
  style: compressed